#!/bin/sh

# Repo location
readonly REPO="${HOME}/.setup"

# Locations of dotfiles
readonly DOTS="${REPO}/dotfiles"
readonly OLD="${REPO}/.backup"

# Script log location
readonly LOG="${REPO}/.install.log"

# Name of metadata CSV files for dotfiles
readonly META='.metadata'

# List of dotfiles used across all platforms
readonly SHARED_DOTFILES=""

# --------------------------------------------------------------
# Parse and create links for all files in a folder
make_symlinks(){
    while read -r line; do
        local link_name=$(echo "${line}" | cut -f1 -d,)
        local link_parent=$(echo "${line}" | cut -f2 -d,)

        # Replace '~' prefix with $HOME
        case "${link_parent}" in
            "~"*)
                link_parent="${HOME}${link_parent#"~"}"
        esac

        # Skip file if it is in backup
        [ $skip_existing ] && [ -e "${OLD}/${1}/${link_name}" ] && { echo "➖ ${1}/${link_name} is already linked, skipping"; continue; }

        if [ -d "${link_parent}" ]; then
            local link="${link_parent}/${link_name}"
            local target="${DOTS}/${1}/${link_name}"

            # Backup existing dotfile
            if [ -f "${link}" ]; then
                [ -d "${OLD}/${1}" ] || { echo "Creating backup folder ${OLD}/${1}"; mkdir -p "${OLD}/${1}"; }
                cp -f "${link}" "${OLD}/${1}/${link_name}"
            fi

            echo "Linking ${target} -> ${link}" | tee -a "${LOG}"
            sudo ln -sf "${target}" "${link}"
        else 
            echo "❌ ${link_parent} does not exist. Is ${1} installed?"
        fi

    done < "${DOTS}/${1}/${META}"
}

# --------------------------------------------------------------
# Configurations specific to Ubuntu on WSL

readonly WINDOWS_USER='me'
readonly WINDOWS_DRIVE='c'
readonly WINDOWS_LINK="${HOME}/win"
readonly DISTRO_NAME='Ubuntu'

# Path to be put in /etc/environment
readonly WSL_ENV_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# List of files to be linked in WSL
readonly WSL_DOTFILES="${SHARED_DOTFILES} wsl"

# Files that must be linked in windows filesystem
readonly WINDOWS_DOTFILES="windows-terminal"

# Create a windows filesystem symlink for use with windows programs
# https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink
make_windows_symlinks(){
    while read -r line; do
        local link_name=$(echo "${line}" | cut -f1 -d,)
        # Windows symlink paths must be relative to windows user home folder
        local link_parent="/mnt/${WINDOWS_DRIVE}/Users/${WINDOWS_USER}/$(echo "${line}" | cut -f2 -d,)"

        # # Skip file if it is in backup
        [ $skip_existing ] && [ -e "${OLD}/${1}/${link_name}" ] && { echo "➖ ${1}/${link_name} is already linked, skipping"; continue; }

        if [ -d "${link_parent}" ]; then
            # Backup if normal file (cant parse windows symlink), otherwise must remove since mklink can't overwrite
            if [ -f "${link_parent}/${link_name}" ]; then
                [ -d "${OLD}/${1}" ] || { echo "Creating backup folder ${OLD}/${1}"; mkdir -p "${OLD}/${1}"; }
                mv -f "${link_parent}/${link_name}" "${OLD}/${1}/${link_name}"
            else
                rm -f "${link_parent}/${link_name}"
            fi

            # Create windows compatible paths for symlink
            local link="${WINDOWS_DRIVE}:\\Users\\${WINDOWS_USER}\\$(cut -f2 -d, "${DOTS}/${1}/${META}" | tr '/' '\\')\\${link_name}"
            local target="\\\\wsl\$\\${DISTRO_NAME}$(echo "${DOTS}/${1}/${link_name}" | tr '/' '\\')"

            # Create symlink using cmd.exe
            cmd.exe /c "mklink ${link} ${target}" 2>> ${LOG}
            [ $? -ne 0 ] && echo "❌ Unable to create symlink for ${1}/${link_name}. Does cmd have admin rights?"
        else 
            echo "❌ ${link_parent} does not exist. Is ${1} installed?"
        fi
    done < "${DOTS}/${1}/${META}"
}

setup_wsl() {

    if [ ! $link_only ]; then
        echo "--------------------------------------------------------------"
        echo "Updating and upgrading packages"
        echo "--------------------------------------------------------------"

        # sudo apt update 2>> ${LOG} && sudo apt upgrade -y 2>> ${LOG}

        echo "--------------------------------------------------------------"
        echo "Configuring SSH"
        echo "--------------------------------------------------------------"

        # ssh-keygen -t rsa -b 4096


        # Packages: nvim, zsh, prompt, rust, exa?

        # Switch to default: nvim, python3, zsh

        
    fi

    echo "--------------------------------------------------------------"
    echo "Creating dotfile symlinks"
    echo "--------------------------------------------------------------"

    # Create link to Windows home
    echo "Linking /mnt/${WINDOWS_DRIVE}/Users/${WINDOWS_USER} -> ${WINDOWS_LINK}" | tee -a "${LOG}"
    ln -sf "/mnt/${WINDOWS_DRIVE}/Users/${WINDOWS_USER}" "${WINDOWS_LINK}"

    for folder in ${WINDOWS_DOTFILES}; do
        make_windows_symlinks $folder
    done

    for folder in ${WSL_DOTFILES}; do
        make_symlinks $folder
    done
}

# --------------------------------------------------------------
# Parse options and execute platform specific configuration

main() {
    # Check repo is in correct location
    [ -d "${REPO}" ] || { echo "${REPO} not found"; exit 1; }
    rm -f ${LOG}

    # Get sudo privileges
    if [ $(sudo printf "") ]; then exit 1; fi

    while getopts "slh" opt; do
        case ${opt} in
            s)
                # Skip linking dotfiles that have been linked before
                skip_existing=1
                ;;
            l)
                # Only link dotfiles, don't perform other operations
                link_only=1
                ;;
            h)
                ;;
            \?)
                ;;
        esac
    done

    setup_wsl
}

main "$@"